spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}?sslmode=disable
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        jdbc.batch_size: 25
        order_updates: true
        order_inserts: true
        connection:
          provider_disables_autocommit: true
    open-in-view: false
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    max-threads: 20
    min-spare-threads: 5
    max-connections: 50

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR

cors:
  allowed-origin-patterns:
    - https://spaced-repetition-coral.vercel.app
    - https://*.vercel.app
    - https://*.now.sh
    - http://localhost:4200