spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: secret
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000  # 24 hours in milliseconds
  application:
    name: spaced-repetition-be
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

cors:
  allowed-origin-patterns:
    - http://localhost:4200
    - https://spaced-repetition-65wojry65-hburaks-projects.vercel.app
