# fly.toml app configuration file generated for spaced-repetetion-be on 2025-02-23T22:06:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spaced-repetetion-be'
primary_region = 'otp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
