app = 'spaced-repetition-be'
primary_region = 'otp'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443

[[vm]]
  size = 'shared-cpu-1x'

[deploy]
  release_command = "java -Dspring.profiles.active=prod -jar /app/app.jar"
