app = 'spaced-repetition-be'
primary_region = 'otp'

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    force_https = true

  [services.concurrency]
    type = "connections"
    hard_limit = 550
    soft_limit = 500

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[deploy]
  release_command = "java -Dspring.profiles.active=prod -jar /app/app.jar"
