app = 'spaced-repetition-be'
primary_region = 'otp'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/api/health"
    protocol = "http"
    timeout = "5s"

[[vm]]
  cpu_kind = "shared"
  size = "shared-cpu-1x"

[env]
  SPRING_PROFILES_ACTIVE = "prod"
