name: Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Make mvnw executable
        run: chmod +x ./spaced-repetetion-be/mvnw
          
      - name: Build with Maven
        run: cd spaced-repetetion-be && ./mvnw clean package -DskipTests
        
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to fly.io
        run: cd spaced-repetetion-be && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 